name: 'docker-build-args'
description: 'Builds arguments list for docker/build-push-action'
author: 'Alex Mukho'
branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  includeVars:
    required: false
    description: 'Action variables for docker arguments list'
  includeSecrets:
    required: false
    description: 'Action secrets for docker arguments list'
  extraArgs:
    required: false
    description: 'Extra values for docker arguments list'

outputs:
  args:
    description: 'Arguments list'

runs:
  using: 'node16'
  main: 'dist/index.js'
